### ISSUE TITLE
Rvt blend gets broken when you duplicate the ExampleOpenLandMap

### ISSUE THREAD

**Issue by delebash** [GameDev4K/unreal-openland#32]
Open Land v 1.13.0

Steps to reproduce

1) Right click on Maps>ExampleOpenLandMap>Select Duplicate
2) Open your duplicate map
3) Select SM_Rock5 in your world outline and press f key to focus on that object

You will notice the rvt sand blend is not working

**Comment by arunoda** [comment]
I just checked that. That's because Unreal Engine removes virtual textures from the Runtime Virtual Texture Volumes when duplicating.
Once you applied them again, it'll work fine as expected.
