### ISSUE TITLE
Can't enable "Enable Texture Variations"

### ISSUE THREAD

**Issue by maks244** [GameDev4K/unreal-openland#40]
I keep getting [these](https://i.imgur.com/UMThkaa.jpeg) errors while trying to enable "Enable Texture Variations"
[SM5] Function MF_OL_Texture_Variation_With_Params: Missing Material Function
[SM5] Function MF_MapAgustments: (Node MakeMaterialattrtutes) Error on property Normal
[SM5] Function MF_MapAgustments: (Node MakeMaterialattrdutes) Error on property BaseColor
[SM5] Function MF_MapAgustments: (Node MakeMaterialattrioutes) Error on property Metalic
[SM5] Function MF_MapAgustments: (Node MakeMaterialattroutes) Error on property Specular
[SM5] Function MF_MapAgustments: (Node MakeMaterialattrioutes) Error on property Roughness
[SM5] Function ME_MapAgustments: (Node MakeMaterialattrbutes) Error on property AmbientOcclusion

**Comment by arunoda** [comment]
I guess there are two issues here.

1) Try enabling Virtual Textures
2) Seems like somehow the `MF_OL_Texture_Variation_With_Params` was changed.

**Comment by maks244** [comment]
I fixed it by reinstalling so I have no idea what the problem was.

**Comment by arunoda** [comment]
Got it. May be you add it while the project is running or so.
I'm gonna close this. Feel free to ask more questions.
